.except-default:
  except:
    variables:
      - $CI_COMMIT_REF_NAME =~ /^docs-/

variables:
  GITLAB_IMAGE: registry.gitlab.com/oceanbolt/obapi/iamserver
  GCR_IMAGE_STAGING: eu.gcr.io/obx-api-staging/obapi/iamserver
  GCR_IMAGE_PROD: eu.gcr.io/obx-api-prod/obapi/iamserver
  GCP_PROJECT_STAGING: obx-api-staging
  GCP_PROJECT_PROD: obx-api-prod

stages:
  - build and test
  - push
  - deploy staging
  - deploy prod

build:
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token registry.gitlab.com --password-stdin
  image: docker:19.03.0
  services:
    - docker:19.03.0-dind
  variables:
    DOCKER_TLS_DIR: "/certs"
    DOCKER_DRIVER: overlay2
  stage: build and test
  only:
    - master
    - merge_requests
  tags:
    - docker
  script:
    - docker pull $GITLAB_IMAGE || true
    - >
      docker build
      --build-arg VCS_REF=$CI_COMMIT_SHA
      --build-arg VCS_URL=$CI_PROJECT_URL
      --tag $GITLAB_IMAGE:$CI_COMMIT_SHA
      .
    - docker push $GITLAB_IMAGE

test:
  image: golang:1.13
  before_script:
    - export ENVKEY=$ENVKEY_TEST
  stage: build and test
  only:
    - master
    - merge_requests
  script:
    - ./test.sh
  after_script:
    - bash <(curl -s https://codecov.io/bash)

push images to gcr staging:
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token registry.gitlab.com --password-stdin
    - docker login -u _json_key --password-stdin https://eu.gcr.io < $GITLAB_DEPLOY_BOT_KEY_STAGING
  image: docker:19.03.0
  services:
    - docker:19.03.0-dind
  stage: push
  only:
    - master
  variables:
    GIT_STRATEGY: none
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker pull $GITLAB_IMAGE:$CI_COMMIT_SHA
    - docker tag $GITLAB_IMAGE:$CI_COMMIT_SHA $GCR_IMAGE_STAGING:$CI_COMMIT_REF_NAME
    - docker push $GCR_IMAGE_STAGING:$CI_COMMIT_REF_NAME
  environment:
    name: staging

push images to gcr prod:
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token registry.gitlab.com --password-stdin
    - docker login -u _json_key --password-stdin https://eu.gcr.io < $GITLAB_DEPLOY_BOT_KEY_PROD
  image: docker:19.03.0
  only:
    - master
  services:
    - docker:19.03.0-dind
  stage: push
  variables:
    GIT_STRATEGY: none
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker pull $GITLAB_IMAGE:$CI_COMMIT_SHA
    - docker tag $GITLAB_IMAGE:$CI_COMMIT_SHA $GCR_IMAGE_PROD:$CI_COMMIT_REF_NAME
    - docker push $GCR_IMAGE_PROD:$CI_COMMIT_REF_NAME
  environment:
    name: production


deploy to staging:
  image: google/cloud-sdk:alpine
  stage: deploy staging
  only:
    - master
  variables:
    GIT_STRATEGY: none
  script:
    - gcloud auth activate-service-account --project=$GCP_PROJECT_STAGING --key-file=$GITLAB_DEPLOY_BOT_KEY_STAGING
    - gcloud components install beta
    - >
      gcloud beta run deploy iamserver
      --image $GCR_IMAGE_STAGING:$CI_COMMIT_REF_NAME
      --platform managed
      --region europe-west1
      --update-env-vars ENVKEY=$ENVKEY_STAGING
      --service-account iamserver-cloud-run@obx-api-staging.iam.gserviceaccount.com
  environment:
    name: staging
    #url: https://api-v2.oceanbolt.com

deploy to prod:
  image: google/cloud-sdk:alpine
  stage: deploy prod
  only:
    - master
  when: manual
  variables:
    GIT_STRATEGY: none
  script:
    - gcloud auth activate-service-account --project=$GCP_PROJECT_PROD --key-file=$GITLAB_DEPLOY_BOT_KEY_PROD
    - gcloud components install beta
    - >
      gcloud beta run deploy iamserver
      --image $GCR_IMAGE_PROD:$CI_COMMIT_REF_NAME
      --platform managed
      --region europe-west1
      --update-env-vars ENVKEY=$ENVKEY_PROD
      --service-account iamserver-cloud-run@obx-api-prod.iam.gserviceaccount.com
  environment:
    name: production
    #url: https://api-staging-v2.internal.oceanbolt.com