variables:
  GITLAB_IMAGE: registry.gitlab.com/oceanbolt/iamserver
  GCR_IMAGE: eu.gcr.io/oceanbolt-infrastructure/iamserver

stages:
  - build
  - push
  - deploy

build:
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token registry.gitlab.com --password-stdin
    - docker login -u _json_key --password-stdin https://eu.gcr.io < $GITLAB_DEPLOY_BOT_KEY
  image: docker:19.03.0
  services:
    - docker:19.03.0-dind
  variables:
    #DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_DIR: "/certs"
    DOCKER_DRIVER: overlay2
  stage: build
  only:
    - master
    - development
    - merge_requests
  tags:
    - docker
  script:
    - docker pull $GITLAB_IMAGE || true
    - >
      docker build
      --build-arg VCS_REF=$CI_COMMIT_SHA
      --build-arg VCS_URL=$CI_PROJECT_URL
      --tag $GITLAB_IMAGE:$CI_COMMIT_SHA
      .
    - docker push $GITLAB_IMAGE


push:
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token registry.gitlab.com --password-stdin
    - docker login -u _json_key --password-stdin https://eu.gcr.io < $GITLAB_DEPLOY_BOT_KEY
  image: docker:19.03.0
  services:
    - docker:19.03.0-dind
  stage: push
  variables:
    # Again, we do not need the source code here. Just playing with Docker.
    GIT_STRATEGY: none
    #DOCKER_HOST: tcp://localhost:2375
    DOCKER_DRIVER: overlay2
    # Create the certificates inside this directory for both the server
    # and client. The certificates used by the client will be created in
    # /certs/client so we only need to share this directory with the
    # volume mount in `config.toml`.
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker pull $GITLAB_IMAGE:$CI_COMMIT_SHA
    - docker tag $GITLAB_IMAGE:$CI_COMMIT_SHA $GCR_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $GCR_IMAGE:$CI_COMMIT_REF_NAME
# Here, the goal is to tag the "master" branch as "latest"

deploy to production:
  image: google/cloud-sdk:alpine
  stage: deploy
  only:
    - master
  variables:
    # Again, we do not need the source code here. Just playing with Docker.
    GIT_STRATEGY: none
  script:
    - gcloud auth activate-service-account --project=oceanbolt-infrastructure --key-file=$GITLAB_DEPLOY_BOT_KEY
    - gcloud components install beta
    - >
      gcloud beta run deploy iamserver
      --image $GCR_IMAGE:$CI_COMMIT_REF_NAME
      --platform managed
      --region europe-west1
      --update-env-vars ENVKEY=$ENVKEY_PROD
  environment:
    name: production
    #url: https://api-v2.oceanbolt.com

deploy to staging:
  image: google/cloud-sdk:alpine
  stage: deploy
  only:
    - development
    - merge_requests
  variables:
    # Again, we do not need the source code here. Just playing with Docker.
    GIT_STRATEGY: none
  script:
    - gcloud auth activate-service-account --project=oceanbolt-infrastructure --key-file=$GITLAB_DEPLOY_BOT_KEY
    - gcloud components install beta
    - echo $ENVKEY_STAGING
    - echo $ENVKEY_PROD
    - >
      gcloud beta run deploy iamserver-staging
      --image $GCR_IMAGE:$CI_COMMIT_REF_NAME
      --platform managed
      --region europe-west1
      --update-env-vars ENVKEY=$ENVKEY_STAGING
  environment:
    name: staging
    #url: https://api-staging-v2.internal.oceanbolt.com
