// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/iam/service.proto

package iam

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/srikrsna/protoc-gen-gotag/tagger"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// User object used to retrieve keys
type User struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty" bson:"user_id,omitempty" datastore:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" datastore:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" datastore:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" datastore:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_b572537561b6c5b6, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type PrivateKey struct {
	Kid                  string   `protobuf:"bytes,1,opt,name=kid,proto3" json:"kid,omitempty" bson:"kid,omitempty" datastore:"kid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" datastore:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" datastore:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" datastore:"-"`
}

func (m *PrivateKey) Reset()         { *m = PrivateKey{} }
func (m *PrivateKey) String() string { return proto.CompactTextString(m) }
func (*PrivateKey) ProtoMessage()    {}
func (*PrivateKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_b572537561b6c5b6, []int{1}
}

func (m *PrivateKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivateKey.Unmarshal(m, b)
}
func (m *PrivateKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivateKey.Marshal(b, m, deterministic)
}
func (m *PrivateKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivateKey.Merge(m, src)
}
func (m *PrivateKey) XXX_Size() int {
	return xxx_messageInfo_PrivateKey.Size(m)
}
func (m *PrivateKey) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivateKey.DiscardUnknown(m)
}

var xxx_messageInfo_PrivateKey proto.InternalMessageInfo

func (m *PrivateKey) GetKid() string {
	if m != nil {
		return m.Kid
	}
	return ""
}

type PublicKey struct {
	Kid                  string   `protobuf:"bytes,1,opt,name=kid,proto3" json:"kid,omitempty" bson:"kid,omitempty" datastore:"kid,omitempty"`
	KeyEnv               string   `protobuf:"bytes,2,opt,name=key_env,json=keyEnv,proto3" json:"key_env,omitempty" bson:"key_env,omitempty" datastore:"key_env,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty" bson:"public_key,omitempty" datastore:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" datastore:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" datastore:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" datastore:"-"`
}

func (m *PublicKey) Reset()         { *m = PublicKey{} }
func (m *PublicKey) String() string { return proto.CompactTextString(m) }
func (*PublicKey) ProtoMessage()    {}
func (*PublicKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_b572537561b6c5b6, []int{2}
}

func (m *PublicKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicKey.Unmarshal(m, b)
}
func (m *PublicKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicKey.Marshal(b, m, deterministic)
}
func (m *PublicKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicKey.Merge(m, src)
}
func (m *PublicKey) XXX_Size() int {
	return xxx_messageInfo_PublicKey.Size(m)
}
func (m *PublicKey) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicKey.DiscardUnknown(m)
}

var xxx_messageInfo_PublicKey proto.InternalMessageInfo

func (m *PublicKey) GetKid() string {
	if m != nil {
		return m.Kid
	}
	return ""
}

func (m *PublicKey) GetKeyEnv() string {
	if m != nil {
		return m.KeyEnv
	}
	return ""
}

func (m *PublicKey) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type UserKey struct {
	Expires              int64    `protobuf:"varint,1,opt,name=expires,proto3" json:"expires,omitempty" bson:"expires,omitempty" datastore:"expires,omitempty"`
	ApikeyId             string   `protobuf:"bytes,2,opt,name=apikey_id,json=apikeyId,proto3" json:"apikey_id,omitempty" bson:"apikey_id,omitempty" datastore:"apikey_id,omitempty"`
	KeyTag               string   `protobuf:"bytes,3,opt,name=key_tag,json=keyTag,proto3" json:"key_tag,omitempty" bson:"key_tag,omitempty" datastore:"key_tag,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty" bson:"user_id,omitempty" datastore:"user_id,omitempty"`
	SigningKeyId         string   `protobuf:"bytes,5,opt,name=signing_key_id,json=signingKeyId,proto3" json:"signing_key_id,omitempty" bson:"signing_key_id,omitempty" datastore:"signing_key_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" datastore:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" datastore:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" datastore:"-"`
}

func (m *UserKey) Reset()         { *m = UserKey{} }
func (m *UserKey) String() string { return proto.CompactTextString(m) }
func (*UserKey) ProtoMessage()    {}
func (*UserKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_b572537561b6c5b6, []int{3}
}

func (m *UserKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserKey.Unmarshal(m, b)
}
func (m *UserKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserKey.Marshal(b, m, deterministic)
}
func (m *UserKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserKey.Merge(m, src)
}
func (m *UserKey) XXX_Size() int {
	return xxx_messageInfo_UserKey.Size(m)
}
func (m *UserKey) XXX_DiscardUnknown() {
	xxx_messageInfo_UserKey.DiscardUnknown(m)
}

var xxx_messageInfo_UserKey proto.InternalMessageInfo

func (m *UserKey) GetExpires() int64 {
	if m != nil {
		return m.Expires
	}
	return 0
}

func (m *UserKey) GetApikeyId() string {
	if m != nil {
		return m.ApikeyId
	}
	return ""
}

func (m *UserKey) GetKeyTag() string {
	if m != nil {
		return m.KeyTag
	}
	return ""
}

func (m *UserKey) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserKey) GetSigningKeyId() string {
	if m != nil {
		return m.SigningKeyId
	}
	return ""
}

type UserKeys struct {
	NumberOfKeys         int64      `protobuf:"varint,1,opt,name=number_of_keys,json=numberOfKeys,proto3" json:"number_of_keys,omitempty"`
	Keys                 []*UserKey `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-" bson:"-" datastore:"-"`
	XXX_unrecognized     []byte     `json:"-" bson:"-" datastore:"-"`
	XXX_sizecache        int32      `json:"-" bson:"-" datastore:"-"`
}

func (m *UserKeys) Reset()         { *m = UserKeys{} }
func (m *UserKeys) String() string { return proto.CompactTextString(m) }
func (*UserKeys) ProtoMessage()    {}
func (*UserKeys) Descriptor() ([]byte, []int) {
	return fileDescriptor_b572537561b6c5b6, []int{4}
}

func (m *UserKeys) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserKeys.Unmarshal(m, b)
}
func (m *UserKeys) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserKeys.Marshal(b, m, deterministic)
}
func (m *UserKeys) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserKeys.Merge(m, src)
}
func (m *UserKeys) XXX_Size() int {
	return xxx_messageInfo_UserKeys.Size(m)
}
func (m *UserKeys) XXX_DiscardUnknown() {
	xxx_messageInfo_UserKeys.DiscardUnknown(m)
}

var xxx_messageInfo_UserKeys proto.InternalMessageInfo

func (m *UserKeys) GetNumberOfKeys() int64 {
	if m != nil {
		return m.NumberOfKeys
	}
	return 0
}

func (m *UserKeys) GetKeys() []*UserKey {
	if m != nil {
		return m.Keys
	}
	return nil
}

type CreateKeyRequest struct {
	Expires              int64    `protobuf:"varint,1,opt,name=expires,proto3" json:"expires,omitempty"`
	KeyTag               string   `protobuf:"bytes,2,opt,name=key_tag,json=keyTag,proto3" json:"key_tag,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" datastore:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" datastore:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" datastore:"-"`
}

func (m *CreateKeyRequest) Reset()         { *m = CreateKeyRequest{} }
func (m *CreateKeyRequest) String() string { return proto.CompactTextString(m) }
func (*CreateKeyRequest) ProtoMessage()    {}
func (*CreateKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b572537561b6c5b6, []int{5}
}

func (m *CreateKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateKeyRequest.Unmarshal(m, b)
}
func (m *CreateKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateKeyRequest.Marshal(b, m, deterministic)
}
func (m *CreateKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateKeyRequest.Merge(m, src)
}
func (m *CreateKeyRequest) XXX_Size() int {
	return xxx_messageInfo_CreateKeyRequest.Size(m)
}
func (m *CreateKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateKeyRequest proto.InternalMessageInfo

func (m *CreateKeyRequest) GetExpires() int64 {
	if m != nil {
		return m.Expires
	}
	return 0
}

func (m *CreateKeyRequest) GetKeyTag() string {
	if m != nil {
		return m.KeyTag
	}
	return ""
}

func (m *CreateKeyRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type UserKeyWithSecret struct {
	Expires              int64    `protobuf:"varint,1,opt,name=expires,proto3" json:"expires,omitempty"`
	ApikeyId             string   `protobuf:"bytes,2,opt,name=apikey_id,json=apikeyId,proto3" json:"apikey_id,omitempty"`
	KeyTag               string   `protobuf:"bytes,3,opt,name=key_tag,json=keyTag,proto3" json:"key_tag,omitempty"`
	ApikeySecret         string   `protobuf:"bytes,4,opt,name=apikey_secret,json=apikeySecret,proto3" json:"apikey_secret,omitempty"`
	UserId               string   `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" datastore:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" datastore:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" datastore:"-"`
}

func (m *UserKeyWithSecret) Reset()         { *m = UserKeyWithSecret{} }
func (m *UserKeyWithSecret) String() string { return proto.CompactTextString(m) }
func (*UserKeyWithSecret) ProtoMessage()    {}
func (*UserKeyWithSecret) Descriptor() ([]byte, []int) {
	return fileDescriptor_b572537561b6c5b6, []int{6}
}

func (m *UserKeyWithSecret) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserKeyWithSecret.Unmarshal(m, b)
}
func (m *UserKeyWithSecret) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserKeyWithSecret.Marshal(b, m, deterministic)
}
func (m *UserKeyWithSecret) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserKeyWithSecret.Merge(m, src)
}
func (m *UserKeyWithSecret) XXX_Size() int {
	return xxx_messageInfo_UserKeyWithSecret.Size(m)
}
func (m *UserKeyWithSecret) XXX_DiscardUnknown() {
	xxx_messageInfo_UserKeyWithSecret.DiscardUnknown(m)
}

var xxx_messageInfo_UserKeyWithSecret proto.InternalMessageInfo

func (m *UserKeyWithSecret) GetExpires() int64 {
	if m != nil {
		return m.Expires
	}
	return 0
}

func (m *UserKeyWithSecret) GetApikeyId() string {
	if m != nil {
		return m.ApikeyId
	}
	return ""
}

func (m *UserKeyWithSecret) GetKeyTag() string {
	if m != nil {
		return m.KeyTag
	}
	return ""
}

func (m *UserKeyWithSecret) GetApikeySecret() string {
	if m != nil {
		return m.ApikeySecret
	}
	return ""
}

func (m *UserKeyWithSecret) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type DeleteKeyRequest struct {
	ApikeyId             string   `protobuf:"bytes,1,opt,name=apikey_id,json=apikeyId,proto3" json:"apikey_id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" datastore:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" datastore:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" datastore:"-"`
}

func (m *DeleteKeyRequest) Reset()         { *m = DeleteKeyRequest{} }
func (m *DeleteKeyRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteKeyRequest) ProtoMessage()    {}
func (*DeleteKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b572537561b6c5b6, []int{7}
}

func (m *DeleteKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteKeyRequest.Unmarshal(m, b)
}
func (m *DeleteKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteKeyRequest.Marshal(b, m, deterministic)
}
func (m *DeleteKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteKeyRequest.Merge(m, src)
}
func (m *DeleteKeyRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteKeyRequest.Size(m)
}
func (m *DeleteKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteKeyRequest proto.InternalMessageInfo

func (m *DeleteKeyRequest) GetApikeyId() string {
	if m != nil {
		return m.ApikeyId
	}
	return ""
}

func (m *DeleteKeyRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type KeyDeletedResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" datastore:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" datastore:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" datastore:"-"`
}

func (m *KeyDeletedResponse) Reset()         { *m = KeyDeletedResponse{} }
func (m *KeyDeletedResponse) String() string { return proto.CompactTextString(m) }
func (*KeyDeletedResponse) ProtoMessage()    {}
func (*KeyDeletedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b572537561b6c5b6, []int{8}
}

func (m *KeyDeletedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyDeletedResponse.Unmarshal(m, b)
}
func (m *KeyDeletedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyDeletedResponse.Marshal(b, m, deterministic)
}
func (m *KeyDeletedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyDeletedResponse.Merge(m, src)
}
func (m *KeyDeletedResponse) XXX_Size() int {
	return xxx_messageInfo_KeyDeletedResponse.Size(m)
}
func (m *KeyDeletedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyDeletedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KeyDeletedResponse proto.InternalMessageInfo

func (m *KeyDeletedResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ValidationResponse struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Permissions          []string `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" datastore:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" datastore:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" datastore:"-"`
}

func (m *ValidationResponse) Reset()         { *m = ValidationResponse{} }
func (m *ValidationResponse) String() string { return proto.CompactTextString(m) }
func (*ValidationResponse) ProtoMessage()    {}
func (*ValidationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b572537561b6c5b6, []int{9}
}

func (m *ValidationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidationResponse.Unmarshal(m, b)
}
func (m *ValidationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidationResponse.Marshal(b, m, deterministic)
}
func (m *ValidationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidationResponse.Merge(m, src)
}
func (m *ValidationResponse) XXX_Size() int {
	return xxx_messageInfo_ValidationResponse.Size(m)
}
func (m *ValidationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidationResponse proto.InternalMessageInfo

func (m *ValidationResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *ValidationResponse) GetPermissions() []string {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "oceanbolt.com.iam.User")
	proto.RegisterType((*PrivateKey)(nil), "oceanbolt.com.iam.PrivateKey")
	proto.RegisterType((*PublicKey)(nil), "oceanbolt.com.iam.PublicKey")
	proto.RegisterType((*UserKey)(nil), "oceanbolt.com.iam.UserKey")
	proto.RegisterType((*UserKeys)(nil), "oceanbolt.com.iam.UserKeys")
	proto.RegisterType((*CreateKeyRequest)(nil), "oceanbolt.com.iam.CreateKeyRequest")
	proto.RegisterType((*UserKeyWithSecret)(nil), "oceanbolt.com.iam.UserKeyWithSecret")
	proto.RegisterType((*DeleteKeyRequest)(nil), "oceanbolt.com.iam.DeleteKeyRequest")
	proto.RegisterType((*KeyDeletedResponse)(nil), "oceanbolt.com.iam.KeyDeletedResponse")
	proto.RegisterType((*ValidationResponse)(nil), "oceanbolt.com.iam.ValidationResponse")
}

func init() { proto.RegisterFile("rpc/iam/service.proto", fileDescriptor_b572537561b6c5b6) }

var fileDescriptor_b572537561b6c5b6 = []byte{
	// 695 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0xcb, 0x6a, 0xdb, 0x40,
	0x14, 0x86, 0xb1, 0x15, 0x3b, 0xf6, 0x89, 0x1b, 0x12, 0xb5, 0xc5, 0xc6, 0x69, 0xc1, 0x28, 0x29,
	0x64, 0x51, 0x14, 0x48, 0xa0, 0x8b, 0xb4, 0xd0, 0x26, 0x4d, 0x68, 0x83, 0x03, 0x0d, 0xca, 0x0d,
	0x4a, 0xa8, 0x33, 0xb6, 0x4f, 0xd4, 0xc1, 0xd6, 0xa5, 0x9a, 0xb1, 0xa9, 0xf7, 0x5d, 0xf5, 0x11,
	0xb2, 0x28, 0xf4, 0xb9, 0xfa, 0x32, 0x65, 0x2e, 0x96, 0x2d, 0x4b, 0xca, 0x2a, 0x2b, 0xa3, 0xf9,
	0xcf, 0x7c, 0x67, 0xe6, 0x3f, 0xbf, 0x25, 0x78, 0x1e, 0x85, 0xbd, 0x1d, 0x4a, 0xbc, 0x1d, 0x86,
	0xd1, 0x98, 0xf6, 0xd0, 0x0e, 0xa3, 0x80, 0x07, 0xe6, 0x7a, 0xd0, 0x43, 0xe2, 0x77, 0x83, 0x21,
	0xb7, 0x7b, 0x81, 0x67, 0x53, 0xe2, 0x35, 0x9f, 0x72, 0xe2, 0xba, 0x18, 0xed, 0xa8, 0x1f, 0x55,
	0x67, 0xdd, 0xc0, 0xd2, 0x25, 0xc3, 0xc8, 0xbc, 0x80, 0xe5, 0x11, 0xc3, 0xa8, 0x43, 0xfb, 0x8d,
	0x42, 0xab, 0xb0, 0x5d, 0x3d, 0x7c, 0x7b, 0xff, 0xeb, 0x8f, 0xf1, 0xa6, 0xcb, 0x02, 0x7f, 0xdf,
	0xd2, 0xca, 0xeb, 0xc0, 0xa3, 0x1c, 0xbd, 0x90, 0x4f, 0xac, 0x56, 0x9f, 0x70, 0xc2, 0x78, 0x10,
	0x61, 0x96, 0xea, 0x94, 0xc5, 0xda, 0x49, 0xdf, 0x3a, 0x07, 0x38, 0x8b, 0xe8, 0x98, 0x70, 0x6c,
	0xe3, 0xc4, 0x3c, 0x06, 0x63, 0x10, 0xf3, 0xf7, 0x04, 0xdf, 0x56, 0xfc, 0x41, 0x2e, 0x3b, 0xa9,
	0x38, 0x62, 0xbf, 0xf5, 0xbb, 0x08, 0xd5, 0xb3, 0x51, 0x77, 0x48, 0x7b, 0x8f, 0x07, 0x15, 0xf7,
	0x1f, 0xe0, 0xa4, 0x83, 0xfe, 0xb8, 0x51, 0x4c, 0xdd, 0x5f, 0x2b, 0x79, 0xb8, 0x94, 0xea, 0x94,
	0x07, 0x38, 0x39, 0xf6, 0xc7, 0xe6, 0x2d, 0x40, 0x28, 0x4f, 0xda, 0x19, 0xe0, 0xa4, 0x61, 0xb4,
	0x0a, 0xdb, 0xb5, 0xc3, 0x03, 0x01, 0x7e, 0xa7, 0xc0, 0x33, 0x31, 0x87, 0x9d, 0x59, 0xe0, 0x54,
	0xc3, 0xe9, 0xf5, 0xad, 0x7f, 0x06, 0x2c, 0x8b, 0x01, 0x0a, 0x2b, 0x2e, 0x61, 0x19, 0x7f, 0x86,
	0x34, 0x42, 0x26, 0xed, 0x30, 0x12, 0x77, 0xd0, 0x4a, 0x4e, 0x9f, 0xb4, 0xea, 0x4c, 0x59, 0xe6,
	0x0d, 0x54, 0x49, 0x48, 0xc5, 0x2d, 0x69, 0x5f, 0x9b, 0xf3, 0x5e, 0x80, 0xf7, 0x15, 0x38, 0xd6,
	0x72, 0xd0, 0x59, 0xba, 0x53, 0x51, 0xab, 0x27, 0xb1, 0xf1, 0x9c, 0xb8, 0xd2, 0x9f, 0xb4, 0xf1,
	0x9c, 0xb8, 0x0f, 0x18, 0x9f, 0x54, 0xa5, 0xf1, 0x17, 0xc4, 0x9d, 0x8f, 0xf3, 0xd2, 0xa3, 0xc5,
	0xd9, 0x0c, 0x60, 0x95, 0x51, 0xd7, 0xa7, 0xbe, 0xdb, 0xd1, 0x76, 0x94, 0x24, 0xfc, 0x44, 0xc0,
	0x8f, 0x14, 0x3c, 0x59, 0x90, 0xd3, 0x23, 0xb7, 0xc8, 0xa9, 0x69, 0xa9, 0x2d, 0xcc, 0xb1, 0x6e,
	0xa1, 0xa2, 0x87, 0xcb, 0xcc, 0x2d, 0x58, 0xf5, 0x47, 0x5e, 0x17, 0xa3, 0x4e, 0x70, 0x27, 0x36,
	0xea, 0x21, 0x3b, 0x35, 0xb5, 0xfa, 0xe5, 0x4e, 0x56, 0xd9, 0xb0, 0x24, 0xb5, 0x62, 0xcb, 0xd8,
	0x5e, 0xd9, 0x6d, 0xda, 0xa9, 0xd7, 0x80, 0xad, 0x81, 0x8e, 0xac, 0xb3, 0xbe, 0xc1, 0xda, 0xc7,
	0x08, 0xd5, 0x1f, 0xd4, 0xc1, 0x1f, 0x23, 0x64, 0xdc, 0x6c, 0x2c, 0xe4, 0x68, 0x16, 0x85, 0xfa,
	0x6c, 0x58, 0x32, 0x08, 0xb1, 0xdf, 0xf5, 0x99, 0xdf, 0x86, 0x12, 0xf4, 0x1b, 0xe0, 0x6f, 0x01,
	0xd6, 0x75, 0xc7, 0x6b, 0xca, 0xbf, 0x9f, 0x63, 0x2f, 0xc2, 0x87, 0x3a, 0x6c, 0xa4, 0xc2, 0x36,
	0x97, 0x95, 0xfa, 0x42, 0x56, 0xe2, 0xf6, 0x9b, 0xf0, 0x44, 0xef, 0x62, 0xb2, 0x81, 0x1a, 0xba,
	0x53, 0x53, 0x8b, 0xba, 0xe9, 0xdc, 0x19, 0x4b, 0x89, 0x33, 0x7e, 0x86, 0xb5, 0x23, 0x1c, 0x62,
	0xc2, 0x83, 0xc4, 0x39, 0x0a, 0xe9, 0x73, 0x4c, 0x49, 0xc5, 0x04, 0xc9, 0x06, 0xb3, 0x8d, 0x13,
	0x05, 0xeb, 0x3b, 0xc8, 0xc2, 0xc0, 0x67, 0x28, 0x6e, 0xeb, 0x21, 0x63, 0xc4, 0x45, 0x4d, 0x9a,
	0x3e, 0x5a, 0xa7, 0x60, 0x5e, 0x91, 0x21, 0xed, 0x13, 0x4e, 0x03, 0x3f, 0xae, 0x7f, 0x06, 0xa5,
	0xb1, 0x58, 0x95, 0xd5, 0x15, 0x47, 0x3d, 0x98, 0x2d, 0x58, 0x09, 0x31, 0xf2, 0x28, 0x63, 0x34,
	0xf0, 0xd5, 0x80, 0xab, 0xce, 0xfc, 0xd2, 0xee, 0xbd, 0x01, 0xe5, 0x03, 0x79, 0x46, 0xf3, 0x03,
	0x54, 0x4e, 0x29, 0xe3, 0x32, 0x12, 0xf5, 0x9c, 0x10, 0x34, 0x37, 0xf2, 0xd3, 0xc1, 0xcc, 0x2b,
	0xa8, 0xc6, 0xc1, 0x30, 0x37, 0x33, 0x2a, 0x17, 0x63, 0xd3, 0xdc, 0xca, 0xc7, 0xcd, 0x8d, 0xfe,
	0x1a, 0xaa, 0xb1, 0xd9, 0x99, 0xdc, 0xc5, 0x51, 0x34, 0x5f, 0x65, 0x14, 0x65, 0xb8, 0x7c, 0x06,
	0x2b, 0xda, 0x4b, 0x89, 0x7e, 0x20, 0xfa, 0x99, 0xc4, 0x8c, 0x39, 0xb4, 0xa1, 0xf6, 0x09, 0xf9,
	0xec, 0x53, 0xf3, 0x32, 0x63, 0xdb, 0xec, 0xf3, 0xd6, 0x7c, 0x91, 0x25, 0x4f, 0x37, 0x1f, 0x96,
	0xbe, 0x1a, 0x94, 0x78, 0xdd, 0xb2, 0xfc, 0xec, 0xee, 0xfd, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xe3,
	0x87, 0x45, 0xcc, 0xb7, 0x07, 0x00, 0x00,
}
